/**
 * Central spam / abuse guard for website form submissions.
 *
 * Every server action that accepts user input (enquiry, promo subscribe,
 * careers) checks submissions against this module BEFORE sending any email.
 *
 * It combines several layers (all compared case-insensitively):
 *
 *   1. exact email addresses          (e.g. "merajuddin36@gmail.com")
 *   2. whole domains                  (e.g. "spamdomain.com") - blocks ALL
 *                                     mailboxes on that domain
 *   3. a broad list of disposable /
 *      throwaway email domains        (mailinator, guerrillamail, etc.)
 *   4. phone / message regex          (e.g. detect repeated link spam)
 *   5. honeypot field                 (a hidden input real users never fill)
 *   6. time trap                      (submit too fast = bot)
 *
 * To unblock a specific sender, remove the matching entry(s) below and redeploy.
 */

const BLOCKED_EMAIL_ADDRESSES = [
  "merajuddin36@gmail.com",
];

const BLOCKED_DOMAINS: string[] = [
  // Manually confirmed spam domains - safe to block the whole domain.
  "uberip.com",
  "drtpone.com",
];

/**
 * Common disposable / throwaway email domains. These offer no real mailbox to
 * reply to, so no legitimate customer should ever use one. Safe to block the
 * whole domain. Add more over time as new ones appear.
 */
const DISPOSABLE_DOMAINS: string[] = [
  "0-mail.com",
  "027168.com",
  "0815.ru",
  "0815.su",
  "0clickemail.com",
  "0wnd.net",
  "0wnd.org",
  "10mail.org",
  "10minutemail.com",
  "10minutemail.net",
  "20minutemail.com",
  "21cn.com",
  "2prong.com",
  "33mail.com",
  "3d-painting.com",
  "4warding.com",
  "4warding.net",
  "4warding.org",
  "5ymail.com",
  "6paq.com",
  "8shield.net",
  "aa5zy64.com",
  "abyssmail.com",
  "adbet.co",
  "addyoutube.com",
  "ag.us.to",
  "agilehq.com",
  "alivance.com",
  "amail4.me",
  "anonaddy.com",
  "anonbox.net",
  "anonymail.dk",
  "anonymousfeedback.net",
  "antispam24.de",
  "armyspy.com",
  "artmail.com",
  "avastbiz.com",
  "avz.dev",
  "aw.kr",
  "bcaoo.com",
  "bearsarefuzzy.com",
  "belamail.org",
  "bestchoiceusedcar.com",
  "bigprofessor.so",
  "binka.me",
  "binkmail.com",
  "binnary.com",
  "bio-muesli.net",
  "bitwhites.top",
  "bizhosting.com",
  "bluebottle.com",
  "bobmail.info",
  "bodhi.lawlita.com",
  "bofthew.com",
  "bootybay.de",
  "boun.cr",
  "bouncr.com",
  "boxformail.in",
  "brcox.com",
  "breakthru.com",
  "brefmail.com",
  "bsnow.net",
  "bunkmail.info",
  "bunsenhoneydew.com",
  "buyusedlibrarybooks.org",
  "buzzcompact.com",
  "c2i.net",
  "cakk.us",
  "cam4you.xyz",
  "card.zp.ua",
  "casualdx.com",
  "cbarkalder.com",
  "cc.li.aura.id",
  "cealliance.org",
  "cellphoneparts.cc",
  "chacuo.net",
  "chammy.info",
  "cheaphub.net",
  "chogmail.com",
  "chong-mail.com",
  "choicemail1.com",
  "chumpstakingdumps.com",
  "cinct.net",
  "citiz.net",
  "cliptik.net",
  "clixser.com",
  "clrmail.com",
  "cmail.com",
  "cmail.org",
  "cnamed.com",
  "cne.tw",
  "coldemail.info",
  "consumerriot.com",
  "courrieltemporaire.com",
  "coza.ro",
  "crankmails.com",
  "crapmail.org",
  "cream.pink",
  "crusthost.com",
  "cu.cc",
  "curryworld.de",
  "cust.in",
  "cuvox.de",
  "dacoolest.com",
  "dandikmail.com",
  "dayrep.com",
  "dcemail.com",
  "deadaddress.com",
  "deadchildren.org",
  "deadspam.com",
  "deekayen.us",
  "defomail.com",
  "deliverme.top",
  "despammed.com",
  "devnullmail.com",
  "dfgh.net",
  "digiposte.fr",
  "dingbone.com",
  "disposableaddress.com",
  "disposableemailaddresses.com",
  "disposableinbox.com",
  "dispose.it",
  "disposeamail.com",
  "disposemail.com",
  "dm.w3internet.co.uk.example.com",
  "dodgeit.com",
  "dodgit.com",
  "dodgit.org",
  "dodsi.com",
  "dolphinnet.net",
  "doogie.it",
  "dontexist.com",
  "dontreg.com",
  "dontsendmespam.de",
  "doqme.com",
  "drdrb.com",
  "drdrb.net",
  "dropmail.me",
  "dspam.de",
  "dynu.net",
  "e4ward.com",
  "easytrashmail.com",
  "edv.to",
  "einrot.com",
  "einrot.de",
  "email-fake.com",
  "emailgo.de",
  "emailias.com",
  "emailinfive.com",
  "emailmiser.com",
  "emailondeck.com",
  "emailproxsy.com",
  "emails.secureserver.net",
  "emailsensei.com",
  "emailtemporario.com.br",
  "emailthe.net",
  "emailtmp.com",
  "emailto.de",
  "emailwarden.com",
  "emailxfer.com",
  "emailz.grapecity.com",
  "emlhub.com",
  "emlpro.com",
  "emltmp.com",
  "envy17.com",
  "ephemail.net",
  "etlgr.com",
  "etranquil.com",
  "etranquil.net",
  "evopo.com",
  "explodemail.com",
  "fakeinbox.com",
  "fakemail.net",
  "fakemailgenerator.com",
  "fakemailz.com",
  "fammix.com",
  "fansworldwide.de",
  "fantasymail.de",
  "fastacura.com",
  "fastchevy.com",
  "fastchrysler.com",
  "fastkawasaki.com",
  "fastmazda.com",
  "fastmitsubishi.com",
  "fastnissan.com",
  "fastsubaru.com",
  "fastsuzuki.com",
  "fasttoyota.com",
  "fastyamaha.com",
  "fbi.gov.com",
  "fetchnet.co.uk",
  "fictionsite.com",
  "fightallspam.com",
  "fivemail.de",
  "fixmail.tk",
  "fizmail.com",
  "fleckens.hu",
  "flemail.com",
  "flurred.com",
  "flyspam.com",
  "flyinggeek.net",
  "foobarbot.net",
  "fr33mail.info",
  "frapmail.com",
  "frosty.fun",
  "fudgerub.com",
  "funtrash.com",
  "fux0ringduh.com",
  "gafy.net",
  "garliclife.com",
  "gellymail.com",
  "get1mail.com",
  "getairmail.com",
  "getmails.eu",
  "getnida.com",
  "getonemail.com",
  "getonemail.net",
  "ghosttexter.de",
  "girlmail.win",
  "gishpuppy.com",
  "glitch.sx",
  "gmal.com",
  "gmx.co",
  "goemailgo.com",
  "gorillamail.com",
  "grandmamail.com",
  "grandmasmail.com",
  "greatdomain.in",
  "greensloth.com",
  "grr.la",
  "gsrv.co.uk",
  "guerrillamail.biz",
  "guerrillamail.com",
  "guerrillamail.de",
  "guerrillamail.info",
  "guerrillamail.net",
  "guerrillamail.org",
  "guerrillamailblock.com",
  "gustr.com",
  "h8s.org",
  "hab-verschlafen.de",
  "hacoo.de",
  "halcyon.com",
  "haltospam.com",
  "happyyou365.com",
  "harakirimail.com",
  "hartbot.de",
  "hasanmail.com",
  "hat-geld.de",
  "hatespam.org",
  "hawrong.com",
  "hazelnut4u.com",
  "hellodream.mobi",
  "herp.in",
  "hidemail.de",
  "hidemyass.com",
  "hidzz.com",
  "hmamail.com",
  "hopemail.biz",
  "hotpop.com",
  "hulapla.de",
  "hurstathletic.com",
  "hws.kr",
  "hypo.allowed.org",
  "ieh-mail.de",
  "ikbenspamvrij.nl",
  "illistnoise.com",
  "imails.info",
  "imho.host",
  "inbax.tk",
  "inbox.si",
  "inboxalias.com",
  "inboxbear.com",
  "inboxcleanup.org",
  "inboxproxy.com",
  "incognitomail.com",
  "incognitomail.net",
  "incognitomail.org",
  "insorg-mail.info",
  "ip6.li",
  "ipoo.org",
  "irish2me.com",
  "iwi.net",
  "jaajmail.com",
  "jeodis.com",
  "jetable.com",
  "jetable.net",
  "jetable.org",
  "jnxjn.com",
  "jobbik.sosoo.info",
  "jopho.com",
  "junk1e.com",
  "junkmail.com",
  "junkmail.org",
  "kamsg.com",
  "kasmail.com",
  "kaspop.com",
  "kebabmail.be",
  "killmail.com",
  "killmail.net",
  "kmail.mooo.com",
  "knol-power.nl",
  "kuku.lu",
  "kulturbetrieb.info",
  "kurzepost.de",
  "l33r.eu",
  "lags.us",
  "landmail.co",
  "lastmail.co",
  "lazyinbox.com",
  "letsmail9.com",
  "letterboxes.org",
  "lixo.com",
  "lixo.ufg.br",
  "login-email.ml",
  "lol.ovpn.to",
  "lookugly.com",
  "lortemail.dk",
  "lr7.us",
  "lroid.com",
  "lubieczac.pl",
  "luckygmaiil.com",
  "lukop.dk",
  "m4ilweb.info",
  "maboard.com",
  "mailed.ro",
  "mailer.fun",
  "mailhaven.com",
  "mailhood.com",
  "mailimate.com",
  "mailin8r.com",
  "mailinator.com",
  "mailinator2.com",
  "mailinator3.com",
  "mailinator4.com",
  "mailinator5.com",
  "mailinator6.com",
  "mailinator7.com",
  "mailinator8.com",
  "mailingaddress.org",
  "mailismagic.com",
  "mailmate.com",
  "mailme.ir",
  "mailmetrash.com",
  "mailmoat.com",
  "mailnator.com",
  "mailnull.com",
  "mailpick.biz",
  "mailproxsy.com",
  "mailquack.com",
  "mailscrap.com",
  "mailshell.com",
  "mailsiphon.com",
  "mailslapping.com",
  "mailslite.com",
  "mailtemp.net",
  "mailtemporaire.com",
  "mailto.de",
  "mailtome.de",
  "mailtothis.com",
  "mailwire.net",
  "mailzilla.com",
  "mailzilla.org",
  "makemenaughty.com",
  "manifestgenerator.com",
  "manybrain.com",
  "martin.ma",
  "masking-malaysia.com",
  "mega.zik.dj",
  "meinspamschutz.de",
  "meltmail.com",
  "meltwaterdirect.com",
  "mepost.pw",
  "merpet.com",
  "messagebeamer.de",
  "metacrawler.com",
  "mfsa.ru",
  "mierdamail.com",
  "mintemail.com",
  "mjukglass.nu",
  "moakt.com",
  "moakt.ws",
  "mobileninjas.com",
  "moburl.com",
  "mockmyid.com",
  "mohmal.com",
  "mohmal.im",
  "mohmal.in",
  "mohmal.tech",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "mt2009.com",
  "mt2014.com",
  "mt2015.com",
  "mtvgt.com",
  "mycard.net.ua",
  "mycleaninbox.net",
  "mymail-in.net",
  "mypacks.net",
  "mypartyclip.de",
  "myphantomemail.com",
  "myspaceinc.com",
  "myspamless.com",
  "mytrashmail.com",
  "mywarnernet.net",
  "n1nja.org",
  "nakedtruth.biz",
  "nanonym.ch",
  "negated.com",
  "neomailbox.com",
  "nepwk.com",
  "nervmich.net",
  "nervtmich.net",
  "netmails.com",
  "netmails.net",
  "netzidiot.de",
  "neverbox.com",
  "nevermail.de",
  "newairmail.com",
  "nicolase.dk",
  "nincsmail.com",
  "nmail.cf",
  "nnhd.host",
  "nobox.pw",
  "noicd.com",
  "nospam.ze.tc",
  "nowmymail.com",
  "nwytg.net",
  "o3enzyme.com",
  "obfus-mail.com",
  "odaymail.com",
  "odnorazovoe.ru",
  "ohi.tw",
  "ok.kz",
  "okclmail.com",
  "oleczka.org",
  "olympus.4pu.com",
  "oneoffemail.com",
  "oneoffmail.com",
  "onlatedotcom.info",
  "oompark.com",
  "opayq.com",
  "ordinaryamerican.net",
  "otherinbox.com",
  "ourklips.com",
  "outlawspam.com",
  "ovpn.to",
  "owlpic.com",
  "pancakemail.com",
  "paplease.com",
  "pcusers.otherinbox.com",
  "pepbot.com",
  "pepvot.com",
  "pjjkp.com",
  "plhk.ru",
  "poczta.onet.pl",
  "pokemail.net",
  "politicaladvocates.com",
  "potencjasosnowiec.pl",
  "poutineyourface.com",
  "poxy4you.com",
  "privacy.net",
  "private-mail.com",
  "proxymail.eu",
  "prtnx.com",
  "prtz.eu",
  "punkass.com",
  "purchase.org",
  "put2.net",
  "putthisinyourspamdatabase.com",
  "pwrby.com",
  "qasti.com",
  "qq.com",
  "quickinbox.com",
  "quickmail.nl",
  "rcpt.at",
  "reallymymail.com",
  "recyclemail.dk",
  "regrl.com",
  "rejectmail.com",
  "reliable-mail.com",
  "remail.cf",
  "rhyta.com",
  "rklips.com",
  "rmqkr.net",
  "rmqqv.com",
  "roletk.in",
  "royal.net",
  "rppkn.com",
  "rtrtr.com",
  "s0ny.net",
  "safe-mail.net",
  "safersignup.de",
  "safetymail.info",
  "safetypostbox.com",
  "sandwhichvideo.com",
  "saynotospams.com",
  "scatmail.com",
  "schafmail.de",
  "schrott-email.de",
  "secretemail.de",
  "secure-mail.biz",
  "secure-link.com",
  "selfdestructingmail.com",
  "sendspamhere.com",
  "sendsrorry.com",
  "sexymail.ovh",
  "sharklasers.com",
  "shieldemail.com",
  "shmeriously.com",
  "shortmail.net",
  "sibmail.com",
  "sinnlos-mail.de",
  "siteposter.net",
  "sizzlemctwizzle.com",
  "skepticaloak.com",
  "slapsfromlastnight.com",
  "sloankettering.com",
  "slopsbox.com",
  "slowfoodgourmet.com",
  "slushmail.com",
  "sms.ouvaton.org",
  "sneakemail.com",
  "snkmail.com",
  "sofort-mail.de",
  "sogetthis.com",
  "sohgmobile.com",
  "soodonims.com",
  "spam.la",
  "spam4.me",
  "spamail.de",
  "spamarrest.com",
  "spambob.com",
  "spambob.net",
  "spambob.org",
  "spambog.com",
  "spambog.de",
  "spambog.ru",
  "spambox.info",
  "spambox.irishspringrealty.com",
  "spambox.us",
  "spamcannon.com",
  "spamcannon.net",
  "spamcero.com",
  "spamcon.org",
  "spamcorptastic.com",
  "spamcowboy.com",
  "spamcowboy.net",
  "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfree24.info",
  "spamfree24.net",
  "spamgoes.in",
  "spamgourmet.com",
  "spamgourmet.net",
  "spamgourmet.org",
  "spamherelots.com",
  "spamify.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com",
  "spamoff.de",
  "spamstack.net",
  "spamthis.co.uk",
  "spamthisplease.com",
  "spamtrail.com",
  "spamtrap.ro",
  "spamwc.de",
  "speed.1s.fr",
  "speedmail.org",
  "spikio.com",
  "spoofmail.de",
  "spraytraynight.com",
  "squizzy.de",
  "ssoia.com",
  "startfu.com",
  "stinkyshorts.com",
  "stopdropandroll.com",
  "storj99.com",
  "stuffmail.de",
  "subpast.com",
  "super-auswahl.de",
  "supergreatmail.com",
  "surfmail.tk",
  "susi.ml",
  "sweetbb.net",
  "sweetxxx.de",
  "t.psh.me",
  "tafmail.com",
  "tagyourself.com",
  "talkinator.com",
  "tapchicuoihoi.com",
  "tarzanmail.cf",
  "teewars.org",
  "teleworm.com",
  "teleworm.us",
  "temp-mail.com",
  "temp-mail.de",
  "temp-mail.org",
  "temp-mailaddress.com",
  "temp-inbox.com",
  "temp-mail.net",
  "tempail.com",
  "tempemail.co.za",
  "tempemail.net",
  "tempinbox.co",
  "tempinbox.com",
  "tempmail.dev",
  "tempmail.io",
  "tempmail.us",
  "tempmail2.com",
  "tempmailo.com",
  "temporaryemail.net",
  "temporaryemail.us",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymailaddress.com",
  "tempshoebox.com",
  "tempthe.net",
  "thankyou2010.com",
  "thc.st",
  "thecloudindex.com",
  "thejoker5.com",
  "thisisnotmyrealemail.com",
  "throwam.com",
  "throwawayemailaddress.com",
  "throwawaymail.com",
  "tilien.com",
  "tittibit.de",
  "tmail.ws",
  "toastMatrix.com",
  "toke.com",
  "topranklist.de",
  "totalvista.com",
  "totesmail.com",
  "tradermail.info",
  "trash-mail.de",
  "trash-me.com",
  "trash2009.com",
  "trash2010.com",
  "trash2011.com",
  "trashdevil.com",
  "trashmail.at",
  "trashmail.com",
  "trashmail.de",
  "trashmail.me",
  "trashmail.net",
  "trashmail.org",
  "trashmail.ws",
  "trashmailer.com",
  "trashymail.com",
  "trbvm.com",
  "trbvn.com",
  "trbvo.com",
  "trillianpro.com",
  "tryalert.com",
  "turual.com",
  "twinmail.de",
  "twocowmail.net",
  "tyldd.com",
  "uacro.com",
  "uggsrock.com",
  "uglymouse.com",
  "uimserv.net",
  "umail.net",
  "unmail.ru",
  "upliftnow.com",
  "uops.org",
  "upm.edu.ph",
  "urbanslug.com",
  "ureee.com",
  "us.af",
  "ushijima1128.cf",
  "utiket.us",
  "valemail.net",
  "vctel.com",
  "veryrealemail.com",
  "viditag.com",
  "viewcastmedia.com",
  "viewcastmedia.net",
  "viewcrate.com",
  "viralnova99.com",
  "vixlet.com",
  "vjtimail.com",
  "vomoto.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",
  "vwvw.de",
  "w3internet.co.uk",
  "walala.org",
  "wasteland.rfc822.org",
  "watchever.biz",
  "webtrip.ch",
  "wegwerfmail.de",
  "wegwerfmail.net",
  "wegwerfmail.org",
  "wetrainbayarea.com",
  "wh4f.org",
  "whyspam.me",
  "wickedgay.uk",
  "wilemail.com",
  "willselfdestruct.com",
  "winemaven.info",
  "winsheep.win",
  "wronghead.com",
  "wuzup.net",
  "wuzupmail.net",
  "wwwnew.eu",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xgmailoo.com",
  "xing886.uu.gl",
  "xjoin.uk",
  "xmail.com",
  "xmaily.com",
  "xoxy.net",
  "xoxox.cc",
  "xoxyjay.com",
  "xyzmail.co",
  "yandere.cu.cc",
  "yapped.net",
  "yeah.net",
  "yep.it",
  "yogamaven.com",
  "yopmail.com",
  "yopmail.fr",
  "yopmail.net",
  "yopmail.org",
  "yopmail.pp.ua",
  "ypmail.webarnak.fr.eu.org",
  "yungplaza.com",
  "z-o-o-m.eu",
  "zehnminutenmail.de",
  "zippymail.info",
  "zoaxe.com",
  "zoemail.org",
  "zomg.info",
  "zoqly.com",
  "zxcvbnm.com",
  "zzz.com",
];

/** Regex run against the enquiry message / phone to catch link-spam patterns. */
const BLOCKED_PATTERNS: RegExp[] = [
  // Coinbase/marketing phishing link-spam hitting the forms.
  /graph\.org\/(Bitcoin|YOU-HAVE-A-NEW)/i,
  /bitcoin[-\s]?mining/i,
];

function normalizeEmailAddress(value: string): string {
  const at = value.indexOf("@");
  if (at < 0) return value.trim().toLowerCase();
  return value.substring(0, at).toLowerCase() + "@" + extractDomain(value);
}

function extractDomain(emailOrDomain: string): string {
  const at = emailOrDomain.lastIndexOf("@");
  const domain = at >= 0 ? emailOrDomain.substring(at + 1) : emailOrDomain;
  return domain.trim().toLowerCase().replace(/^\.+|\.+$/g, "");
}

function matchesAnyAddress(email: string): boolean {
  const check = normalizeEmailAddress(email);
  return BLOCKED_EMAIL_ADDRESSES.some(
    (blocked) => normalizeEmailAddress(blocked) === check,
  );
}

function matchesAnyDomain(emailOrDomain: string): boolean {
  const domain = extractDomain(emailOrDomain);
  return (
    BLOCKED_DOMAINS.some((blocked) => blockDomainRule(blocked, domain)) ||
    DISPOSABLE_DOMAINS.some((blocked) => blockDomainRule(blocked, domain))
  );
}

function blockDomainRule(blocked: string, submittedDomain: string): boolean {
  const b = blocked.trim().toLowerCase();
  return (
    submittedDomain === b ||
    submittedDomain.endsWith("." + b) // also blocks subdomains
  );
}

/**
 * Returns true when a submission must be silently dropped (blocked).
 * `email` is required; `message`/`phone` are optional and only checked
 * if provided.
 */
export function shouldBlockSubmission(input: {
  email?: string;
  message?: string;
  phone?: string;
}): boolean {
  if (input.email && (matchesAnyAddress(input.email) || matchesAnyDomain(input.email))) {
    return true;
  }

  const textToScan = [input.message, input.phone].filter(Boolean).join("\n");
  if (textToScan) {
    for (const pattern of BLOCKED_PATTERNS) {
      if (pattern.test(textToScan)) return true;
    }
  }

  return false;
}

/**
 * Minimum time in milliseconds a real human should take to fill out a form.
 * Bots auto-submit in milliseconds; anything faster than this is treated as
 * automated spam. Generous to avoid false-positives for fast typists who use
 * password managers / autofill.
 */
const MIN_HUMAN_TIME_MS = 3_000;

/**
 * The shared, invisible field names used by every client form for the honeypot
 * and the time trap. Both are wired up in the form components.
 */
export const HONEYPOT_FIELD = "company_website";
export const TIME_TRAP_FIELD = "loaded_at";

/**
 * Full anti-spam gate for a server action. Combines every layer:
 * blocklist email/domain/pattern checks PLUS a honeypot field (a hidden input
 * a real human never fills) PLUS a time trap (submission must not be faster
 * than a human can type).
 *
 * Actions should pass the raw values straight from FormData:
 *
 *   shouldBlockForm({
 *     email: data.email,
 *     phone: ...,
 *     message: ...,
 *     honeypot: data[HONEYPOT_FIELD],
 *     startedAt: data[TIME_TRAP_FIELD],
 *   })
 *
 * Returns true when the submission must be silently dropped.
 */
export function shouldBlockForm(input: {
  email?: string;
  message?: string;
  phone?: string;
  honeypot?: string;
  startedAt?: string;
}): boolean {
  // Layer 5: honeypot - any value means a bot filled the invisible field.
  if (input.honeypot && input.honeypot.trim().length > 0) {
    return true;
  }

  // Layer 6: time trap - submitted too fast to be human.
  const started = Number(input.startedAt);
  if (Number.isFinite(started) && started > 0) {
    const elapsed = Date.now() - started;
    if (elapsed >= 0 && elapsed < MIN_HUMAN_TIME_MS) {
      return true;
    }
  }

  // Layers 1-4: blocklist email/domain + disposed domains + message/phone regex.
  return shouldBlockSubmission({
    email: input.email,
    phone: input.phone,
    message: input.message,
  });
}

export const spamGuard = {
  blockedEmailCount:
    BLOCKED_EMAIL_ADDRESSES.length +
    BLOCKED_DOMAINS.length +
    DISPOSABLE_DOMAINS.length +
    BLOCKED_PATTERNS.length,
};
