export type LegacyRedirect = {
  source: string;
  destination: string;
  statusCode: 301;
};

// Validated against the live app: every destination maps to an existing
// car detail page, /brands/ brand page, blog article, or static page.
// No chains, no loops, no homepage fallbacks. Sources already handled in
// next.config.ts and URLs with no valid replacement (410) are excluded.
export const legacyRedirects: LegacyRedirect[] = [
  { source: "/audi/rent-audi-r8-spyder", destination: "/rent-audi-dubai/audi-r8-spyder", statusCode: 301 },
  { source: "/bentley/rent-bentley-continental-gt", destination: "/rent-bentley-dubai/bentley-continental-gt", statusCode: 301 },
  { source: "/bentley/rent-bentley-continental-gtc", destination: "/rent-bentley-dubai/bentley-continental-gtc", statusCode: 301 },
  { source: "/blog/16", destination: "/blog", statusCode: 301 },
  { source: "/blog/3", destination: "/blog", statusCode: 301 },
  { source: "/blog/5", destination: "/blog", statusCode: 301 },
  { source: "/blog/7", destination: "/blog", statusCode: 301 },
  { source: "/blog/8", destination: "/blog", statusCode: 301 },
  { source: "/blog/page/3", destination: "/blog", statusCode: 301 },
  { source: "/bmw/rent-bmw-m3-competition", destination: "/rent-bmw-dubai/bmw-m3-competition", statusCode: 301 },
  { source: "/bmw/rent-bmw-m4-competition", destination: "/rent-bmw-dubai/bmw-m4-competition", statusCode: 301 },
  { source: "/bmw/rent-bmw-x7-m50i", destination: "/rent-bmw-dubai/bmw-x7-m50i", statusCode: 301 },
  { source: "/bmw/rent-bmw-x7-m60i", destination: "/rent-bmw-dubai/bmw-x7-m60i", statusCode: 301 },
  { source: "/brands/rent-audi-dubai/r8-facelift-spyder", destination: "/rent-audi-dubai/audi-r8-spyder", statusCode: 301 },
  { source: "/brands/rent-audi-dubai/r8-facelift-spyder/feed", destination: "/rent-audi-dubai/audi-r8-spyder", statusCode: 301 },
  { source: "/brands/rent-bentley-dubai/feed", destination: "/brands/rent-bentley-dubai", statusCode: 301 },
  { source: "/brands/rent-cadillac-dubai/feed", destination: "/brands/rent-cadillac-dubai", statusCode: 301 },
  { source: "/brands/rent-ferrari-dubai/f8-tributo", destination: "/rent-ferrari-dubai/ferrari-f8-tributo-spyder-yellow", statusCode: 301 },
  { source: "/brands/rent-ferrari-dubai/feed", destination: "/brands/rent-ferrari-dubai", statusCode: 301 },
  { source: "/brands/rent-lamborghini-dubai/feed", destination: "/brands/rent-lamborghini-dubai", statusCode: 301 },
  { source: "/cadillac/rent-cadillac-escalade-sports-platinum-2023", destination: "/rent-cadillac-dubai/cadillac-escalade-sports-platinum", statusCode: 301 },
  { source: "/car-rental-guide-what-you-need-to-know-before-renting-a-supercar", destination: "/blogs/renting-a-lamborghini-guide", statusCode: 301 },
  { source: "/cars/audi-r3", destination: "/rent-audi-dubai/audi-rs3", statusCode: 301 },
  { source: "/cars/bmw-m4-competition", destination: "/rent-bmw-dubai/bmw-m4-competition", statusCode: 301 },
  { source: "/cars/ferrari-f8-tributo", destination: "/rent-ferrari-dubai/ferrari-f8-tributo-spyder-yellow", statusCode: 301 },
  { source: "/cars/maserati-mc-20", destination: "/rent-maserati-dubai/maserati-mc20", statusCode: 301 },
  { source: "/cars/porsche-911-gt3", destination: "/rent-porsche-dubai/porsche-911-gt3", statusCode: 301 },
  { source: "/cars/rent-ferrari-488-dubai", destination: "/rent-ferrari-dubai/ferrari-488-spyder-white", statusCode: 301 },
  { source: "/color/black/feed", destination: "/our-fleet", statusCode: 301 },
  { source: "/color/black/page/2", destination: "/our-fleet", statusCode: 301 },
  { source: "/color/candy-purple", destination: "/our-fleet", statusCode: 301 },
  { source: "/color/gray", destination: "/our-fleet", statusCode: 301 },
  { source: "/color/purple", destination: "/our-fleet", statusCode: 301 },
  { source: "/color/white", destination: "/our-fleet", statusCode: 301 },
  { source: "/ferrari/rent-ferrari-488-spyder-white", destination: "/rent-ferrari-dubai/ferrari-488-spyder-white", statusCode: 301 },
  { source: "/ferrari/rent-ferrari-f8-tributo-spider-novitec-2022", destination: "/rent-ferrari-dubai/ferrari-f8-tributo-spider-novitec", statusCode: 301 },
  { source: "/ferrari/rent-ferrari-sf90-stradale", destination: "/rent-ferrari-dubai/ferrari-sf90-stradale", statusCode: 301 },
  { source: "/lamborghini/rent-lamborghini-aventador-svj-roadster-2022", destination: "/rent-lamborghini-dubai/lamborghini-aventador-svj-roadster", statusCode: 301 },
  { source: "/lamborghini/rent-lamborghini-huracan-coupe", destination: "/rent-lamborghini-dubai/lamborghini-huracan-coupe", statusCode: 301 },
  { source: "/lamborghini/rent-lamborghini-huracan-coupe/feed", destination: "/rent-lamborghini-dubai/lamborghini-huracan-coupe", statusCode: 301 },
  { source: "/lamborghini/rent-lamborghini-huracan-evo-coupe", destination: "/rent-lamborghini-dubai/lamborghini-huracan-evo-coupe", statusCode: 301 },
  { source: "/lamborghini/rent-lamborghini-huracan-sto", destination: "/rent-lamborghini-dubai/lamborghini-huracan-sto", statusCode: 301 },
  { source: "/lamborghini/rent-lamborghini-urus-mansory", destination: "/rent-lamborghini-dubai/lamborghini-urus-mansory", statusCode: 301 },
  { source: "/maserati/rent-maserati-mc20", destination: "/rent-maserati-dubai/maserati-mc20", statusCode: 301 },
  { source: "/mclaren/rent-mclaren-570s", destination: "/rent-mclaren-dubai/mclaren-570s", statusCode: 301 },
  { source: "/mclaren/rent-mclaren-570s-spyder", destination: "/rent-mclaren-dubai/mclaren-570s-spyder", statusCode: 301 },
  { source: "/mclaren/rent-mclaren-720s-novitec-spyder-2023", destination: "/rent-mclaren-dubai/mclaren-720s-novitec-spyder", statusCode: 301 },
  { source: "/mclaren/rent-mclaren-720s-performance", destination: "/rent-mclaren-dubai/mclaren-720s-performance", statusCode: 301 },
  { source: "/mercedes/mercedes-glc-63s-amg-coupe", destination: "/rent-mercedes-benz-dubai/mercedes-glc-63s-amg-coupe", statusCode: 301 },
  { source: "/mercedes/mercedes-gls600-maybach", destination: "/rent-mercedes-benz-dubai/mercedes-gls600-maybach", statusCode: 301 },
  { source: "/mercedes/rent-mercedes-brabus-g63-700-widestar", destination: "/rent-mercedes-benz-dubai/mercedes-brabus-amg-g63-700-widestar", statusCode: 301 },
  { source: "/mercedes/rent-mercedes-brabus-g63-800-widestar", destination: "/rent-mercedes-benz-dubai/mercedes-brabus-g63-800-widestar", statusCode: 301 },
  { source: "/our-fleet/5/page/3", destination: "/our-fleet", statusCode: 301 },
  { source: "/our-fleet/5/page/4", destination: "/our-fleet", statusCode: 301 },
  { source: "/our-fleet/5/page/5", destination: "/our-fleet", statusCode: 301 },
  { source: "/our-fleet/5/page/6", destination: "/our-fleet", statusCode: 301 },
  { source: "/our-fleet/6", destination: "/our-fleet", statusCode: 301 },
  { source: "/our-fleet/7", destination: "/our-fleet", statusCode: 301 },
  { source: "/our-fleet/7/page/2", destination: "/our-fleet", statusCode: 301 },
  { source: "/our-fleet/7/page/6", destination: "/our-fleet", statusCode: 301 },
  { source: "/porsche/porsche-911-gt3-rs", destination: "/rent-porsche-dubai/porsche-911-gt3-rs", statusCode: 301 },
  { source: "/porsche/rent-porsche-911-carerra-s-spyder", destination: "/rent-porsche-dubai/porsche-911-carerra-s-spyder", statusCode: 301 },
  { source: "/porsche/rent-porsche-911-gt3-2022", destination: "/rent-porsche-dubai/porsche-911-gt3", statusCode: 301 },
  { source: "/porsche/rent-porsche-macan-sports", destination: "/rent-porsche-dubai/porsche-macan-sports", statusCode: 301 },
  { source: "/privacy-policy-2", destination: "/privacy-policy", statusCode: 301 },
  { source: "/rent-audi-dubai/audi-r8-spyder/feed", destination: "/rent-audi-dubai/audi-r8-spyder", statusCode: 301 },
  { source: "/rent-audi-dubai/audi-rs3/feed", destination: "/rent-audi-dubai/audi-rs3", statusCode: 301 },
  { source: "/rent-bentley-dubai/bentley-bentayga-black/feed", destination: "/rent-bentley-dubai/bentley-bentayga-black", statusCode: 301 },
  { source: "/rent-bentley-dubai/bentley-bentayga-brown/feed", destination: "/rent-bentley-dubai/bentley-bentayga-brown", statusCode: 301 },
  { source: "/rent-bentley-dubai/bentley-bentayga-mansory/feed", destination: "/rent-bentley-dubai/bentley-bentayga-mansory", statusCode: 301 },
  { source: "/rent-bmw-dubai/bmw-735i/feed", destination: "/rent-bmw-dubai/bmw-735i", statusCode: 301 },
  { source: "/rent-bmw-dubai/bmw-x6-m-competition-blue/feed", destination: "/rent-bmw-dubai/bmw-x6-m-competition-blue", statusCode: 301 },
  { source: "/rent-bmw-dubai/bmw-x6-m-competition-red/feed", destination: "/rent-bmw-dubai/bmw-x6-m-competition-red", statusCode: 301 },
  { source: "/rent-bmw-dubai/bmw-x7-m50i/feed", destination: "/rent-bmw-dubai/bmw-x7-m50i", statusCode: 301 },
  { source: "/rent-cadillac-dubai/cadillac-escalade-sports-platinum/feed", destination: "/rent-cadillac-dubai/cadillac-escalade-sports-platinum", statusCode: 301 },
  { source: "/rent-ferrari-dubai/ferrari-488-spyder-white/feed", destination: "/rent-ferrari-dubai/ferrari-488-spyder-white", statusCode: 301 },
  { source: "/rent-ferrari-dubai/ferrari-f8-tributo-spyder-yellow/feed", destination: "/rent-ferrari-dubai/ferrari-f8-tributo-spyder-yellow", statusCode: 301 },
  { source: "/rent-ferrari-dubai/ferrari-purosangue/feed", destination: "/rent-ferrari-dubai/ferrari-purosangue", statusCode: 301 },
  { source: "/rent-lamborghini-dubai/lamborghini-huracan-evo-spyder-yellow/feed", destination: "/rent-lamborghini-dubai/lamborghini-huracan-evo-spyder-yellow", statusCode: 301 },
  { source: "/rent-luxury-cars-dubai/page/1", destination: "/rent-luxury-cars-dubai", statusCode: 301 },
  { source: "/rent-luxury-cars-dubai/page/5", destination: "/rent-luxury-cars-dubai", statusCode: 301 },
  { source: "/rent-luxury-cars-dubai/page/7", destination: "/rent-luxury-cars-dubai", statusCode: 301 },
  { source: "/rent-maserati-dubai/maserati-mc20/feed", destination: "/rent-maserati-dubai/maserati-mc20", statusCode: 301 },
  { source: "/rent-mclaren-dubai/mclaren-720s-spyder-white/feed", destination: "/rent-mclaren-dubai/mclaren-720s-spyder-white", statusCode: 301 },
  { source: "/rent-mclaren-dubai/mclaren-720s/feed", destination: "/rent-mclaren-dubai/mclaren-720s", statusCode: 301 },
  { source: "/rent-mclaren-dubai/mclaren-750s-spyder-tiffany-blue/feed", destination: "/rent-mclaren-dubai/mclaren-750s-spyder-tiffany-blue", statusCode: 301 },
  { source: "/rent-mclaren-dubai/mclaren-artura-spyder/feed", destination: "/rent-mclaren-dubai/mclaren-artura-spyder", statusCode: 301 },
  { source: "/rent-mclaren-dubai/mclaren-artura/feed", destination: "/rent-mclaren-dubai/mclaren-artura", statusCode: 301 },
  { source: "/rent-mercedes-benz-dubai/mercedes-benz-amg-c63/feed", destination: "/rent-mercedes-benz-dubai/mercedes-benz-amg-c63", statusCode: 301 },
  { source: "/rent-mercedes-benz-dubai/mercedes-benz-amg-g63-800-brabus/feed", destination: "/rent-mercedes-benz-dubai/mercedes-brabus-g63-800-widestar", statusCode: 301 },
  { source: "/rent-mercedes-benz-dubai/mercedes-benz-amg-gls800-brabus/feed", destination: "/rent-mercedes-benz-dubai/mercedes-benz-amg-gls800-brabus", statusCode: 301 },
  { source: "/rent-mercedes-benz-dubai/mercedes-brabus-amg-g63-700-widestar/feed", destination: "/rent-mercedes-benz-dubai/mercedes-brabus-amg-g63-700-widestar", statusCode: 301 },
  { source: "/rent-mercedes-benz-dubai/mercedes-v250-vip-line/feed", destination: "/rent-mercedes-benz-dubai/mercedes-v250-vip-line", statusCode: 301 },
  { source: "/rent-porsche-dubai/porsche-911-gt3-white/feed", destination: "/rent-porsche-dubai/porsche-911-gt3-white", statusCode: 301 },
  { source: "/rent-rolls-royce-dubai/rolls-royce-wraith-black-badge/feed", destination: "/rent-rolls-royce-dubai/rolls-royce-wraith-black-badge", statusCode: 301 },
  { source: "/rent-sports-cars-dubai/page/1", destination: "/rent-sports-cars-dubai", statusCode: 301 },
  { source: "/rolls-royce/rent-rolls-royce-cullinan-mansory", destination: "/rent-rolls-royce-dubai/rolls-royce-cullinan-mansory", statusCode: 301 },
  { source: "/rolls-royce/rent-rolls-royce-wraith-black-badge", destination: "/rent-rolls-royce-dubai/rolls-royce-wraith-black-badge", statusCode: 301 },
  { source: "/rolls-royce/rolls-royce-cullinan", destination: "/rent-rolls-royce-dubai/rolls-royce-cullinan", statusCode: 301 },
  { source: "/the-history-of-the-iconic-bentley-logo", destination: "/blogs/history-of-bentley-logo", statusCode: 301 },
];
