// Legacy WordPress URLs with no current replacement on the site.
// Returned as HTTP 410 Gone via proxy.ts (runs before redirects).
export const legacyGonePaths = [
  "/ar/my-account/",
  "/bmw/rent-bmw-x6-m-competition-2022-2",
  "/brands/rent-maserati-dubai/levante",
  "/cars-seats/2/",
  "/cars-seats/2/page/3/",
  "/cars-seats/7/",
  "/cars/bentley-gt-rental",
  "/cars/range-rover-svr-dubai",
  "/cars/rent-ford-mustang-convertible-dubai",
  "/comments/feed/",
  "/ferrari/rent-ferrari-f8-tributo-spyder",
  "/lamborghini/rent-lamborghini-huracan-evo-spyder",
  "/lamborghini/rent-lamborghini-huracan-evo-spyder-2022",
  "/lamborghini/rent-lamborghini-urus",
  "/lamborghini/rent-lamborghini-urus-2021",
  "/mercedes/mercedes-maybach-s560",
  "/mercedes/rent-mercedes-benz-g63-amg-2021-2",
  "/mercedes/rent-mercedes-benz-g63-amg-2021-3",
  "/product-tag/911-gt3/",
  "/product/4097/",
  "/range-rover/rent-range-rover-svr-2021-2",
  "/rent-bentley-dubai/bentley-bentayga-2022-copy",
  "/rent-electric-cars-dubai/feed",
  "/rent-range-rover-dubai/range-rover-svr-orange/feed",
  "/rolls-royce/rent-rolls-royce-dawn-2021-2",
  "/rolls-royce/rent-rolls-royce-dawn-2021-3",
  "/user/",
  "/what-happened-when-whats-on-rented-a-lamborghini",
  "/wp-json/",
] as const;
